remote_theme: jekyll/minima
plugins: 
  - jekyll-remote-theme
title: Ryan Allen
description: PhD candidate at HBS
logo: https://github.com/ryanthomasallen/ryanthomasallen.github.io/blob/main/ryan_allen_portrait.jpg?raw=true
# Analytics
google_analytics: G-2VE8B6C6RX

