theme: jekyll-theme-minimal
title: Ryan Allen
description: PhD candidate at HBS
logo: https://github.com/ryanthomasallen/ryanthomasallen.github.io/blob/main/ryan_allen_portrait.jpg?raw=true
# Analytics
analytics:
  provider               : "google-gtag"
  google:
    measurement_id          : G-TJ9G9NFN8Q

