theme: jekyll-theme-minimal
title: Ryan Allen
description: Ryan Allen | Harvard Business School
logo: https://github.com/ryanthomasallen/ryanthomasallen.github.io/blob/main/ryan_allen_portrait.jpg?raw=true
# Analytics
google_analytics: G-2VE8B6C6RX
url: https://www.ryantallen.com


